name: Talk-point CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.11.1

    - name: Install dependencies
      working-directory: ./backend
      run: pnpm install --frozen-lockfile
    
    - name: Build project
      working-directory: ./backend
      run: pnpm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-artifacts
        path: |
          backend/dist
          backend/package.json
          backend/pnpm-lock.yaml

  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
