name: Talk-point CI

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ staging, main, master ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ staging, main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']
      
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.1
        run_install: false

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Run Linting
      working-directory: ./frontend
      run: pnpm lint

    - name: Build Project
      working-directory: ./frontend
      run: pnpm build
